spring.application.name=auth-microservice

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.application.name=employees

# Data Source Settings
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=pass

# H2 Console Settings - THIS IS THE KEY
spring.h2.console=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port 8081
spring.server.port=8081

#Client and server ids
spring.client.id=${CLIENT_ID}
spring.client.secret=${CLIENT_SECRET}

spring.server.public=${SERVER_KEY_PUB}
spring.server.private=${SERVER_KEY_PRIV}
